from enum import Enum


REQ_CREDENTIAL = "REQ_CREDENTIAL"
REQ_PRESENTATION = "REQ_PRESENTATION"
DID_INIT = "DID_INIT"
REQ_REVOCATION = "REQ_REVOCATION"


class ClaimRequestType(Enum):
    CREDENTIAL = REQ_CREDENTIAL
    PRESENTATION = REQ_PRESENTATION
    INIT = DID_INIT
    REVOCATION = REQ_REVOCATION
