class PropertyName:
    ALGO_KEY_RSA = "RS256"
    ALGO_KEY_ECDSA = "ES256"
    ALGO_KEY_ECDSAK = "ES256K"

    EC_CURVE_PARAM_SECP256R1 = "secp256r1"
    EC_CURVE_PARAM_SECP256K1 = "secp256k1"

    KEY_DOCUMENT_CONTEXT = "@context"
    KEY_VERSION = "version"
    KEY_DOCUMENT_ID = "id"
    KEY_DOCUMENT_CREATED = "created"
    KEY_DOCUMENT_UPDATED = "updated"
    KEY_DOCUMENT_PUBLICKEY = "publicKey"
    KEY_DOCUMENT_PUBLICKEY_ID = "id"
    KEY_DOCUMENT_PUBLICKEY_TYPE = "type"
    KEY_DOCUMENT_PUBLICKEY_HEX = "publicKeyHex"
    KEY_DOCUMENT_PUBLICKEY_BASE64 = "publicKeyBase64"
    KEY_DOCUMENT_PUBLICKEY_CREATED = "created"
    KEY_DOCUMENT_PUBLICKEY_REVOKED = "revoked"
    KEY_DOCUMENT_AUTHENTICATION = "authentication"
    KEY_DOCUMENT_AUTHENTICATION_PUBLICKEY = "publicKey"
    KEY_DOCUMENT_AUTHENTICATION_TYPE = "type"

    VALUE_DOCUMENT_CONTEXT = "https://w3id.org/did/v1"

    # Update Transaction
    KEY_TX_UPDATE_METHOD = "method"
    KEY_TX_UPDATE_METHOD_ADDKEY = "addKey"
    KEY_TX_UPDATE_METHOD_REVOKEKEY = "revokeKey"
    KEY_TX_UPDATE_PARAM = "param"
